# Generated by Django 3.1.3 on 2020-11-14 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/items')),
                ('min_bid', models.FloatField()),
                ('max_bid', models.FloatField()),
                ('final_bid', models.FloatField()),
                ('promoted', models.CharField(choices=[('PRO', 'Promoted'), ('COM', 'Common')], max_length=25)),
                ('auction_start', models.DateTimeField(auto_now_add=True)),
                ('auction_end', models.DateTimeField()),
                ('views_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='images/logos')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('phone_number', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=45)),
                ('post_code', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=45)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('account_status', models.CharField(choices=[('ACT', 'Active'), ('INA', 'Inactive'), ('BLK', 'Blocked')], max_length=25)),
                ('account_type', models.CharField(choices=[('PRE', 'Premium'), ('Nor', 'Normal')], max_length=25)),
                ('avatar', models.ImageField(blank=True, upload_to='images/avatars')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_rating', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=1)),
                ('seller_comment', models.CharField(max_length=255)),
                ('buyer_rating', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=1)),
                ('buyer_comment', models.CharField(max_length=255)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.auction')),
            ],
        ),
        migrations.CreateModel(
            name='BuyNow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_time', models.DateTimeField()),
                ('bid', models.FloatField()),
                ('auction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.auction')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_time', models.DateTimeField()),
                ('bid', models.FloatField()),
                ('auction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.auction')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.auction')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.profile')),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auctionapp.category'),
        ),
        migrations.AddField(
            model_name='auction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auctionapp.profile'),
        ),
    ]
