# Generated by Django 3.1.3 on 2020-11-10 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/items')),
                ('min_bid', models.FloatField()),
                ('max_bid', models.FloatField()),
                ('final_bid', models.FloatField()),
                ('promoted', models.CharField(choices=[('PRO', 'Promoted'), ('COM', 'Common')], max_length=25)),
                ('auction_start', models.DateTimeField(auto_now_add=True)),
                ('auction_end', models.DateTimeField()),
                ('views_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='images/logos')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=45)),
                ('post_code', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('login_email', models.EmailField(max_length=254, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('account_status', models.CharField(choices=[('ACT', 'Active'), ('INA', 'Inactive'), ('BLK', 'Blocked')], max_length=25)),
                ('avatar', models.ImageField(blank=True, upload_to='images/avatars')),
                ('account_type', models.CharField(choices=[('PRE', 'Premium'), ('Nor', 'Normal')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_rating', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=1)),
                ('seller_comment', models.CharField(max_length=255)),
                ('buyer_rating', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=1)),
                ('buyer_comment', models.CharField(max_length=255)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.auctiondetails')),
            ],
        ),
        migrations.CreateModel(
            name='BuyNow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_time', models.DateTimeField()),
                ('bid', models.FloatField()),
                ('auction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.auctiondetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_time', models.DateTimeField()),
                ('bid', models.FloatField()),
                ('auction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.auctiondetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.auctiondetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='auctiondetails',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auctionapp.category'),
        ),
        migrations.AddField(
            model_name='auctiondetails',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auctionapp.user'),
        ),
    ]
