# Generated by Django 3.1.3 on 2020-11-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0002_auto_20201115_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_status',
        ),
    ]
