# Generated by Django 3.1.3 on 2020-11-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0003_remove_profile_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='final_bid',
            field=models.FloatField(null=True),
        ),
    ]
