# Generated by Django 3.1.3 on 2020-11-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0005_auto_20201121_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='final_bid',
            field=models.FloatField(),
        ),
    ]
