# Generated by Django 3.1.3 on 2020-11-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0006_auto_20201122_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='final_bid',
            field=models.FloatField(null=True),
        ),
    ]
