# Generated by Django 3.1.3 on 2020-11-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0009_auto_20201123_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='auction_id',
            new_name='auction',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='user_id',
            new_name='user',
        ),
    ]
