# Generated by Django 3.1.3 on 2020-11-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0010_auto_20201127_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='final_bid',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
