# Generated by Django 3.1.3 on 2020-11-28 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0011_auto_20201128_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buynow',
            old_name='auction_id',
            new_name='auction',
        ),
        migrations.RenameField(
            model_name='buynow',
            old_name='user_id',
            new_name='user',
        ),
    ]
