# Generated by Django 3.1.3 on 2020-11-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0012_auto_20201128_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_active',
            field=models.BooleanField(default=True),
        ),
    ]
