# Generated by Django 3.1.3 on 2020-12-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0013_auction_auction_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='final_bid',
            field=models.FloatField(default=0),
        ),
    ]
